stages:
  - build
  - test
  - bench

build:
  stage: build
  script:
    # Dependency for node-replication
    - sudo apt install libhwloc-dev gnuplot libfuse-dev liburcu-dev liburcu6 pkg-config --yes
    - cd benches; cargo build; cd ..
    - cd cnr; cargo build; cd ..
    - cd nr; cargo build; cd ..

test:
  stage: test
  script:
    - cd cnr; timeout 1h cargo test; cd ..
    - cd nr; timeout 1h cargo test; cd ..
    - cd benches; cargo bench --no-run; cd ..
  dependencies:
    - build
  variables:
    GIT_STRATEGY: fetch

benchmark:skylake2x:
  stage: bench
  script:
    - bash scripts/ci.bash
  dependencies:
    - test
  variables:
    GIT_STRATEGY: fetch
  tags:
    - skylake2x

benchmark:skylake4x:
  stage: bench
  script:
    - bash scripts/ci.bash
  dependencies:
    - test
  variables:
    GIT_STRATEGY: fetch
  tags:
    - skylake4x
