name: Compile and Test NR

on:
  push:
    paths:
      - nr/**
      - benches/**

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest

    steps:
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y libhwloc-dev gnuplot libfuse-dev liburcu-dev liburcu6
    - name: Update URCI
      run: |
        wget http://mirrors.kernel.org/ubuntu/pool/main/libu/liburcu/liburcu6_0.11.1-2_amd64.deb
        wget http://mirrors.kernel.org/ubuntu/pool/main/libu/liburcu/liburcu-dev_0.11.1-2_amd64.deb
        sudo dpkg -i liburcu-dev_0.11.1-2_amd64.deb liburcu6_0.11.1-2_amd64.deb
    - uses: actions/checkout@v1
    - name: Install rust toolchain
      run: rustup show
    - name: Build NR
      run: cargo build --release --verbose
      working-directory: ./nr
    - name: Compile tests
      run: cargo test --release --no-run --verbose
      working-directory: ./nr
    - name: Compile benchmarks
      run: |
        cargo bench --bench log --features="nr" --no-run --verbose
        cargo bench --bench synthetic --features="nr" --no-run --verbose
        cargo bench --bench stack --features="nr" --no-run --verbose
        cargo bench --bench hashmap --features="nr" --no-run --verbose
        cargo bench --bench vspace --features="nr" --no-run --verbose
      working-directory: ./benches
    - name: Try the stack example
      run: RUST_BACKTRACE=1 RUST_LOG='trace' cargo run --release --example stack -- -t1,2 --nop 100000 -l 1 -m sequential
      working-directory: ./nr
    - name: Run clippy
      uses: actions-rs/clippy-check@v1
      args: --all-features --manifest-path nr/Cargo.toml
      with:
        token: ${{ secrets.GITHUB_TOKEN }}