name: Compile and Test

on: [push]

jobs:
  build:
    name: Build and test on ${{ matrix.os }} with rustc ${{ matrix.rust }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        rust: [nightly]

    steps:
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y libhwloc-dev gnuplot libfuse-dev liburcu-dev liburcu6
    - name: Update URCI
      run: |
        wget http://mirrors.kernel.org/ubuntu/pool/main/libu/liburcu/liburcu6_0.11.1-2_amd64.deb
        wget http://mirrors.kernel.org/ubuntu/pool/main/libu/liburcu/liburcu-dev_0.11.1-2_amd64.deb
        sudo dpkg -i liburcu-dev_0.11.1-2_amd64.deb liburcu6_0.11.1-2_amd64.deb
    - name: Set up a Rust toolchain
      uses: hecrj/setup-rust-action@v1.0.2
      with:
        rust-version: ${{ matrix.rust }}
    - uses: actions/checkout@v1
    - name: Build
      run: cargo build --release --verbose
    - name: Try to compile tests
      run: cargo test --release --no-run --verbose
    - name: Try to compile benchmarks
      run: cargo bench --no-run --verbose
    - name: Try stack example
      run: RUST_BACKTRACE=1 RUST_LOG='trace' cargo run --release --example stack -- -t1,2 --nop 100000 -l 1 -m sequential
